name: Docker CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ritiklrt2/portfolio:latest .

      - name: Push Docker image
        run: |
          docker push ritiklrt2/portfolio:latest
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            # Login to Docker Hub (or your registry)
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
            docker pull ritiklrt2/portfolio:latest
            docker stop portfolio || true
            docker rm portfolio || true
            docker run -d -p 3001:3000 --name portfolio ritiklrt2/portfolio:latest
